version: "3"
services:
  app:
    container_name: "python_container"
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python_container
    volumes:
      - $PWD:/home/work
    ports:
      - "8888:8888"
    tty: true
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8889 --NotebookApp.token=''
